import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Next js Concepts",
    template: "%s | Next jsconcepts", // %s will be replaced with children title only if absolute title object is not specified in child page
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-8`}>
        <header className="bg-blue-300 p-4">
          <p>header</p>
        </header>
        <section className="text-green-500">{children}</section>
        <footer className="bg-slate-300 p-4">
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
