/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hor7Ak8QDhw
 */
import { CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"

export function TaskForm() {
  return (
    <Card>
      <CardHeader className="pb-0">
        <div>Add Task</div>
        <div>Fill out the form below to add a new task.</div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="title">Title</Label>
          <Input id="title" placeholder="Enter the title" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="description">Description</Label>
          <Textarea id="description" placeholder="Enter the description" required />
        </div>
        <div className="space-y-2">
          <Label>Priority</Label>
          <div className="w-24">
            <Select>
              <SelectTrigger>
                <Button className="w-full justify-between text-left" type="button" variant="outline">
                  <span>Choose</span>
                  <div className="ml-2 w-4 h-4" />
                </Button>
              </SelectTrigger>
              <SelectContent className="mt-1 p-0">
                <SelectItem value="low">Low</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="high">High</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="space-y-2">
          <Label>Status</Label>
          <div className="w-24">
            <Select>
              <SelectTrigger>
                <Button className="w-full justify-between text-left" type="button" variant="outline">
                  <span>Choose</span>
                  <div className="ml-2 w-4 h-4" />
                </Button>
              </SelectTrigger>
              <SelectContent className="mt-1 p-0">
                <SelectItem value="todo">To Do</SelectItem>
                <SelectItem value="inprogress">In Progress</SelectItem>
                <SelectItem value="done">Done</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </CardContent>
      <CardFooter className="pt-0">
        <Button className="ml-auto">Add Task</Button>
      </CardFooter>
    </Card>
  )
}
